language: ruby

rvm:
  - 2.1

branches:
  except:
    - ontohub.org
    - staging.ontohub.org
    - develop.ontohub.org

services:
  - redis-server

notifications:
  email: false

before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'gem install bundler'

script:
  - bundle exec rake cucumber
  - bundle exec rake test:coveralls

before_script:
  - psql -c 'create database ontohub_test;' -U postgres
  - sudo apt-add-repository -y ppa:hets/hets
  - sudo apt-add-repository -y 'deb http://archive.canonical.com/ubuntu precise partner'
  - sudo apt-add-repository -y 'deb http://archive.ubuntu.com/ubuntu precise-updates main restricted universe multiverse'
  - sudo apt-get update
  - sudo apt-get install libsane libgphoto2-2 hets-core subversion udrawgraph git-svn
  - sudo hets -update
  - RAILS_ENV=test bundle exec rake db:migrate || true
  - RAILS_ENV=test bundle exec rake sunspot:solr:start
