# Hets environment. The first matching item in the lists is used.
hets_path:
  - /usr/bin/hets
  - ~/dev/hets/hets
  - /opt/local/bin/hets
  - ~/code/hets/hets
  - ~/ontohub/Hets/hets
hets_lib:
  - /usr/lib/hets/hets-lib
  - ~/dev/hets/lib
  - ~/ontohub/Hets
hets_owl_tools:
  - /usr/lib/hets/hets-owl-tools
  - ~/dev/hets/OWL2
  - ~/code/hets/OWL2
  - ~/ontohub/Hets/OWL2

