# Hets environment. The first matching item in the lists is used.
hets_path:
  - /usr/lib/hets/hets
  - ~/dev/hets/hets
hets_lib:
  - /usr/lib/hets/hets-lib
  - ~/dev/hets/lib
hets_owl_tools:
  - /usr/lib/hets/hets-owl-tools
  - ~/dev/hets/OWL2
