search:
  paths:
    - "app/controllers"
    - "app/helpers"
    - "app/presenters"
    - "app/views"
    - "app/models"
    - "lib"

ignore_unused:
  - activerecord.*
  - date.*
  - simple_form.*
  - time.*
  - '*.help*'
  - '*.placeholder*'
  - repository.access.*
  - Mapping
  - LogicMapping

ignore_missing:
  - views.pagination.*
  - help
  - placeholder
  - simple_form.*
